###
GET http://localhost:8005/alphaApp/api/v1/rate/rub
Content-Type: application/json
###
GET http://localhost:8005/alphaApp/api/v1/rate/rub.json

###
GET http://localhost:8005/alphaApp/api/v1/rate/azn
Content-Type: application/json
###
GET http://localhost:8005/alphaApp/api/v1/rate/azn.json

###
GET http://localhost:8005/alphaApp/api/v1/rate/gbp
Content-Type: application/json
###
GET http://localhost:8005/alphaApp/api/v1/rate/gbp.json

###
GET http://localhost:8005/alphaApp/api/v1/rate/jpy
Content-Type: application/json
###
GET http://localhost:8005/alphaApp/api/v1/rate/jpy.json
