###
GET http://localhost:8005/alphaApp/api/v1/rate/rub
Content-Type: application/json
###
GET http://localhost:8005/alphaApp/api/v1/rate/rub.json

###
GET http://localhost:8005/alphaApp/api/v1/rate/azh
Content-Type: application/json
###
GET http://localhost:8005/alphaApp/api/v1/rate/azh.json

###
GET http://localhost:8005/alphaApp/api/v1/rate/gbp
Content-Type: application/json
###
GET http://localhost:8005/alphaApp/api/v1/rate/gbp.json


###
GET http://localhost:8008/testApp/api/v1/rate/jpy
Content-Type: application/json
###
GET http://localhost:8008/testApp/api/v1/rate/jpy.json
